apiVersion: v2
name: gigshub
description: A Helm chart for GigsHub - Freelance Marketplace Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - gigshub
  - marketplace
  - mern
maintainers:
  - name: GigsHub Team
home: https://github.com/JainamSavla/GigsHub
