apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gigshub.fullname" . }}-prometheus-config
  labels:
    {{- include "gigshub.labels" . | nindent 4 }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'gigshub-k8s-monitor'

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'gigshub-api'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: api
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "5000"
          - source_labels: [__address__]
            target_label: __address__
            replacement: $1:5000
