{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gigshub.fullname" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: gigshub-api
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gigshub-api
  endpoints:
    - port: http
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "gigshub.fullname" . }}-mongodb
  namespace: {{ .Release.Namespace }}
  labels:
    app: gigshub-mongodb
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gigshub-mongodb
  endpoints:
    - port: mongodb
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
