apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gigshub
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/JainamSavla/GigsHub
    targetRevision: gitops
    path: .
    helm:
      valueFiles:
      - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: gigshub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
