{{- if .Values.client.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gigshub.fullname" . }}-client
  labels:
    app: client
    {{- include "gigshub.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
        imagePullPolicy: {{ .Values.client.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.client.service.port }}
          name: http
        resources:
          {{- toYaml .Values.client.resources | nindent 10 }}
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
{{- end }}
